### ISSUE TITLE
Linux Environment

### ISSUE THREAD

**Issue by blacky0x0** [stevekm/nf-dashboard#3]
Please share the information about environment.

I've got the following issue:
```
java -version 
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)

nfbroadcast git:(master) ✗ make
./gradlew compile exportClasspath
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :nxf-commons:compileGroovy
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/home/blacky/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy/2.5.1/e9628b90c92dcfc7cfaf2f987a2dd2fdabbb3dd5/groovy-2.5.1.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
startup failed:
General error during conversion: java.lang.UnsupportedOperationException

java.lang.UnsupportedOperationException
        at groovyjarjarasm.asm.ClassVisitor.visitNestMemberExperimental(ClassVisitor.java:248)
        at groovyjarjarasm.asm.ClassReader.accept(ClassReader.java:651)
        at groovyjarjarasm.asm.ClassReader.accept(ClassReader.java:391)
        at org.codehaus.groovy.ast.decompiled.AsmDecompiler.parseClass(AsmDecompiler.java:83)
        at org.codehaus.groovy.control.ClassNodeResolver.findDecompiled(ClassNodeResolver.java:254)
        at org.codehaus.groovy.control.ClassNodeResolver.tryAsLoaderClassOrScript(ClassNodeResolver.java:192)
        at org.codehaus.groovy.control.ClassNodeResolver.findClassNode(ClassNodeResolver.java:172)
        at org.codehaus.groovy.control.ClassNodeResolver.resolveName(ClassNodeResolver.java:128)
        at org.codehaus.groovy.control.ResolveVisitor.resolveToOuter(ResolveVisitor.java:742)
        at org.codehaus.groovy.control.ResolveVisitor.resolve(ResolveVisitor.java:392)
        at org.codehaus.groovy.control.ResolveVisitor.visitClass(ResolveVisitor.java:1332)
        at org.codehaus.groovy.control.ResolveVisitor.startResolving(ResolveVisitor.java:219)
        at org.codehaus.groovy.tools.javac.JavaAwareCompilationUnit$1.call(JavaAwareCompilationUnit.java:76)
        at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1087)
        at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:631)
        at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:609)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:586)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:565)
        at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:179)
        at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:57)
        at org.gradle.api.internal.tasks.compile.GroovyCompilerFactory$DaemonSideCompiler.execute(GroovyCompilerFactory.java:77)
        at org.gradle.api.internal.tasks.compile.GroovyCompilerFactory$DaemonSideCompiler.execute(GroovyCompilerFactory.java:65)
        at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerCallable.call(AbstractDaemonCompiler.java:88)
        at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerCallable.call(AbstractDaemonCompiler.java:76)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:42)
        at org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:46)
        at org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:30)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:101)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.base/java.lang.Thread.run(Thread.java:834)

General error during conversion: java.lang.UnsupportedOperationException

> Task :nxf-commons:compileGroovy FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':nxf-commons:compileGroovy'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 53s
2 actionable tasks: 2 executed
Makefile:35: recipe for target 'compile' failed
make: *** [compile] Error 1
```

**Comment by blacky0x0** [comment]
Also I have no `pg_ctl` and no `PGDIR` because Postgres was installed from linux distros. How can I execute the `install` step without that?

**Comment by stevekm** [comment]
It will take me some time to completely look into this but off the top of my head, I should note this section in the `Makefile`:

```
nfbroadcast:
	@echo ">>> Setting up Nextflow nfbroadcast..."
	git clone https://github.com/qbicsoftware/nextflow.git nfbroadcast && \
	cd nfbroadcast && \
	git checkout nfbroadcast && \
	make
```

This was used before the Nextflow `weblog` feature was completed as part of Nextflow, so this branch may still be using an older version of Nextflow that still requires Java 8 and may not have been fully compatible with newer versions of Java. Its on my to-do list to update this repo to use a mainstream version of Nextflow instead. 

I do most development for these things on my Mac so I will have to set up a Linux test environment to try it out as well, that is where I got the path to use for `PGDIR`, if you have a different path you should be able to set it from the command line; `make setup-db PGDIR=/path/to/postgresdir`

**Comment by blacky0x0** [comment]
I've successfully installed and run the dashboard. Just switched to Java 8 and executed the commands manually. Thanks for the help!
